version: "3.9"
   
services:
  db:
    image: postgres:14
    container_name: chat_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=halkiestalkies_db
      - POSTGRES_USER=halkiestalkies_user
      - POSTGRES_PASSWORD=halkiestalkies_pass
      - POSTGRES_PORT=5434

  redis:
    image: redis:latest
    container_name: chat_redis
    ports:
      - "6380:6379"

  web:
    container_name: chat_app
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python manage.py makemigrations --merge --noinput & python manage.py migrate & python manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/app
    ports:
      - "8001:8000"