version: "3.9"
   
services:
  db:
    image: postgres:14
    container_name: chat_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=halkiestalkies_db
      - POSTGRES_USER=halkiestalkies_user
      - POSTGRES_PASSWORD=halkiestalkies_pass
      - POSTGRES_PORT=5434

  redis:
    image: redis:6.2-alpine
    container_name: chat_redis
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    command:
      - 'redis-server'

  daphne:
    container_name: chat_daphne
    build:
      context: .
      dockerfile: ./Dockerfile
    command: daphne -b 0.0.0.0 -p 8001 HalkiesTalkies.asgi:application
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis

  web:
    container_name: chat_app
    build: 
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py collectstatic --no-input && daphne -b 0.0.0.0 -p 8000 HalkiesTalkies.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis